push will fail now if Q gate fails

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -56,10 +56,9 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
       # Optional: Step 7: Check Quality Gate
-      # Uncomment this step if you want to fail the workflow if the Quality Gate fails
-      # - name: Check Quality Gate
-      #   run: |
-      #     curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MohitShukla_basis" > quality_gate.json
-      #     if [ "$(jq -r '.projectStatus.status' quality_gate.json)" != "OK" ]; then
-      #       echo "Quality Gate failed!"
-      #       exit 1
+      - name: Check Quality Gate
+        run: |
+          curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MohitShukla_basis" > quality_gate.json
+          if [ "$(jq -r '.projectStatus.status' quality_gate.json)" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
