disabled sonar check in workflow temporarily

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -32,9 +32,9 @@ jobs:
             -Dsonar.projectKey=MohitShukla_basis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Ensure this secret is defined in your repository
-      - name: Check Quality Gate
-        run: |
-          curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MohitShukla_basis" > quality_gate.json
-          if [ "$(jq -r '.projectStatus.status' quality_gate.json)" != "OK" ]; then
-            echo "Quality Gate failed!"
-            exit 1
+      # - name: Check Quality Gate
+      #   run: |
+      #     curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MohitShukla_basis" > quality_gate.json
+      #     if [ "$(jq -r '.projectStatus.status' quality_gate.json)" != "OK" ]; then
+      #       echo "Quality Gate failed!"
+      #       exit 1
